"""empty message

Revision ID: 2abbb762b832
Revises: 5675f3d020f1
Create Date: 2021-04-30 16:48:10.444736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abbb762b832'
down_revision = '5675f3d020f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'commentLINK')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('commentLINK', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
