"""empty message

Revision ID: 30724730d283
Revises: d7a905ff4e5d
Create Date: 2021-04-20 15:56:28.705374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30724730d283'
down_revision = 'd7a905ff4e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventNAME', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposalNAME', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('winner', sa.Boolean(), nullable=True),
    sa.Column('eventID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eventID'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vote', sa.Column('eventID', sa.Integer(), nullable=False))
    op.add_column('vote', sa.Column('userID', sa.Integer(), nullable=False))
    op.drop_constraint('vote_usersIDs_fkey', 'vote', type_='foreignkey')
    op.create_foreign_key(None, 'vote', 'user', ['userID'], ['id'])
    op.create_foreign_key(None, 'vote', 'event', ['eventID'], ['id'])
    op.create_foreign_key(None, 'vote', 'proposal', ['proposalID'], ['id'])
    op.drop_column('vote', 'proposalNAME')
    op.drop_column('vote', 'winner')
    op.drop_column('vote', 'usersIDs')
    op.drop_column('vote', 'votesCOUNT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('votesCOUNT', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('vote', sa.Column('usersIDs', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('vote', sa.Column('winner', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('vote', sa.Column('proposalNAME', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.create_foreign_key('vote_usersIDs_fkey', 'vote', 'user', ['usersIDs'], ['id'])
    op.drop_column('vote', 'userID')
    op.drop_column('vote', 'eventID')
    op.drop_table('proposal')
    op.drop_table('event')
    # ### end Alembic commands ###
